name = "random-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_id = "4d73fc80e8ba34643f7a1c85dbf26fc9" }
main = "worker.js"
usage_model = "unbound"
compatibility_date = "2022-08-23"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]
